[package]
name = "davies-chess"
version = "0.1.1"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
ruci = { version = "2.1.0", features = ["gui-sync"] }
shakmaty = "^0.27"

[profile.release]
debug = true
